version: '3.7'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file: .env

  backend:
    build: ./
    command: "/usr/src/app/init.sh"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    privileged: true
    ports:
      - "8000:8000"
    depends_on:
      - db
